
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://likqtzcrdffksdwykxdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpa3F0emNyZGZma3Nkd3lreGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDQ3MjYsImV4cCI6MjA1OTA4MDcyNn0.Eo3QR1Y6yBnAe4Guo6eL8dvrh3ek3PNPhFhrfVIxRPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
